//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsolvencyService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://www.rechtspraak.nl/namespaces/cir01", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.rechtspraak.nl/namespaces/cir01", ConfigurationName="InsolvencyService.CIRSoap")]
    public interface CIRSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rechtspraak.nl/namespaces/cir01/searchByDate", ReplyAction="*")]
        System.Threading.Tasks.Task<InsolvencyService.searchByDateResponse> searchByDateAsync(InsolvencyService.searchByDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rechtspraak.nl/namespaces/cir01/searchInsolvencyID", ReplyAction="*")]
        System.Threading.Tasks.Task<InsolvencyService.searchInsolvencyIDResponse> searchInsolvencyIDAsync(InsolvencyService.searchInsolvencyIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rechtspraak.nl/namespaces/cir01/searchNaturalPerson", ReplyAction="*")]
        System.Threading.Tasks.Task<InsolvencyService.searchNaturalPersonResponse> searchNaturalPersonAsync(InsolvencyService.searchNaturalPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rechtspraak.nl/namespaces/cir01/searchUndertaking", ReplyAction="*")]
        System.Threading.Tasks.Task<InsolvencyService.searchUndertakingResponse> searchUndertakingAsync(InsolvencyService.searchUndertakingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rechtspraak.nl/namespaces/cir01/searchModifiedSince", ReplyAction="*")]
        System.Threading.Tasks.Task<InsolvencyService.searchModifiedSinceResponse> searchModifiedSinceAsync(InsolvencyService.searchModifiedSinceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rechtspraak.nl/namespaces/cir01/searchRemovedSince", ReplyAction="*")]
        System.Threading.Tasks.Task<InsolvencyService.searchRemovedSinceResponse> searchRemovedSinceAsync(InsolvencyService.searchRemovedSinceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rechtspraak.nl/namespaces/cir01/getCase", ReplyAction="*")]
        System.Threading.Tasks.Task<InsolvencyService.getCaseResponse> getCaseAsync(InsolvencyService.getCaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rechtspraak.nl/namespaces/cir01/GetLastUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<InsolvencyService.GetLastUpdateResponse> GetLastUpdateAsync(InsolvencyService.GetLastUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rechtspraak.nl/namespaces/cir01/searchReportsSince", ReplyAction="*")]
        System.Threading.Tasks.Task<InsolvencyService.searchReportsSinceResponse> searchReportsSinceAsync(InsolvencyService.searchReportsSinceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rechtspraak.nl/namespaces/cir01/getCaseWithReports", ReplyAction="*")]
        System.Threading.Tasks.Task<InsolvencyService.getCaseWithReportsResponse> getCaseWithReportsAsync(InsolvencyService.getCaseWithReportsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchByDateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchByDate", Namespace="http://www.rechtspraak.nl/namespaces/cir01", Order=0)]
        public InsolvencyService.searchByDateRequestBody Body;
        
        public searchByDateRequest()
        {
        }
        
        public searchByDateRequest(InsolvencyService.searchByDateRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.rechtspraak.nl/namespaces/cir01")]
    public partial class searchByDateRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string court;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public InsolvencyService.ArrayOfString pubType;
        
        public searchByDateRequestBody()
        {
        }
        
        public searchByDateRequestBody(System.DateTime date, string court, InsolvencyService.ArrayOfString pubType)
        {
            this.date = date;
            this.court = court;
            this.pubType = pubType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchByDateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchByDateResponse", Namespace="http://www.rechtspraak.nl/namespaces/cir01", Order=0)]
        public InsolvencyService.searchByDateResponseBody Body;
        
        public searchByDateResponse()
        {
        }
        
        public searchByDateResponse(InsolvencyService.searchByDateResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.rechtspraak.nl/namespaces/cir01")]
    public partial class searchByDateResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement searchByDateResult;
        
        public searchByDateResponseBody()
        {
        }
        
        public searchByDateResponseBody(System.Xml.XmlElement searchByDateResult)
        {
            this.searchByDateResult = searchByDateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchInsolvencyIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchInsolvencyID", Namespace="http://www.rechtspraak.nl/namespaces/cir01", Order=0)]
        public InsolvencyService.searchInsolvencyIDRequestBody Body;
        
        public searchInsolvencyIDRequest()
        {
        }
        
        public searchInsolvencyIDRequest(InsolvencyService.searchInsolvencyIDRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.rechtspraak.nl/namespaces/cir01")]
    public partial class searchInsolvencyIDRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insolvencyID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string court;
        
        public searchInsolvencyIDRequestBody()
        {
        }
        
        public searchInsolvencyIDRequestBody(string insolvencyID, string court)
        {
            this.insolvencyID = insolvencyID;
            this.court = court;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchInsolvencyIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchInsolvencyIDResponse", Namespace="http://www.rechtspraak.nl/namespaces/cir01", Order=0)]
        public InsolvencyService.searchInsolvencyIDResponseBody Body;
        
        public searchInsolvencyIDResponse()
        {
        }
        
        public searchInsolvencyIDResponse(InsolvencyService.searchInsolvencyIDResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.rechtspraak.nl/namespaces/cir01")]
    public partial class searchInsolvencyIDResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement searchInsolvencyIDResult;
        
        public searchInsolvencyIDResponseBody()
        {
        }
        
        public searchInsolvencyIDResponseBody(System.Xml.XmlElement searchInsolvencyIDResult)
        {
            this.searchInsolvencyIDResult = searchInsolvencyIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchNaturalPersonRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchNaturalPerson", Namespace="http://www.rechtspraak.nl/namespaces/cir01", Order=0)]
        public InsolvencyService.searchNaturalPersonRequestBody Body;
        
        public searchNaturalPersonRequest()
        {
        }
        
        public searchNaturalPersonRequest(InsolvencyService.searchNaturalPersonRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.rechtspraak.nl/namespaces/cir01")]
    public partial class searchNaturalPersonRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string prefix;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string surname;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime dateOfBirth;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string postalCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int houseNumber;
        
        public searchNaturalPersonRequestBody()
        {
        }
        
        public searchNaturalPersonRequestBody(string prefix, string surname, System.DateTime dateOfBirth, string postalCode, int houseNumber)
        {
            this.prefix = prefix;
            this.surname = surname;
            this.dateOfBirth = dateOfBirth;
            this.postalCode = postalCode;
            this.houseNumber = houseNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchNaturalPersonResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchNaturalPersonResponse", Namespace="http://www.rechtspraak.nl/namespaces/cir01", Order=0)]
        public InsolvencyService.searchNaturalPersonResponseBody Body;
        
        public searchNaturalPersonResponse()
        {
        }
        
        public searchNaturalPersonResponse(InsolvencyService.searchNaturalPersonResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.rechtspraak.nl/namespaces/cir01")]
    public partial class searchNaturalPersonResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement searchNaturalPersonResult;
        
        public searchNaturalPersonResponseBody()
        {
        }
        
        public searchNaturalPersonResponseBody(System.Xml.XmlElement searchNaturalPersonResult)
        {
            this.searchNaturalPersonResult = searchNaturalPersonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchUndertakingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchUndertaking", Namespace="http://www.rechtspraak.nl/namespaces/cir01", Order=0)]
        public InsolvencyService.searchUndertakingRequestBody Body;
        
        public searchUndertakingRequest()
        {
        }
        
        public searchUndertakingRequest(InsolvencyService.searchUndertakingRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.rechtspraak.nl/namespaces/cir01")]
    public partial class searchUndertakingRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string commercialRegisterID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string postalCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int houseNumber;
        
        public searchUndertakingRequestBody()
        {
        }
        
        public searchUndertakingRequestBody(string name, string commercialRegisterID, string postalCode, int houseNumber)
        {
            this.name = name;
            this.commercialRegisterID = commercialRegisterID;
            this.postalCode = postalCode;
            this.houseNumber = houseNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchUndertakingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchUndertakingResponse", Namespace="http://www.rechtspraak.nl/namespaces/cir01", Order=0)]
        public InsolvencyService.searchUndertakingResponseBody Body;
        
        public searchUndertakingResponse()
        {
        }
        
        public searchUndertakingResponse(InsolvencyService.searchUndertakingResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.rechtspraak.nl/namespaces/cir01")]
    public partial class searchUndertakingResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement searchUndertakingResult;
        
        public searchUndertakingResponseBody()
        {
        }
        
        public searchUndertakingResponseBody(System.Xml.XmlElement searchUndertakingResult)
        {
            this.searchUndertakingResult = searchUndertakingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchModifiedSinceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchModifiedSince", Namespace="http://www.rechtspraak.nl/namespaces/cir01", Order=0)]
        public InsolvencyService.searchModifiedSinceRequestBody Body;
        
        public searchModifiedSinceRequest()
        {
        }
        
        public searchModifiedSinceRequest(InsolvencyService.searchModifiedSinceRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.rechtspraak.nl/namespaces/cir01")]
    public partial class searchModifiedSinceRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime modifyDate;
        
        public searchModifiedSinceRequestBody()
        {
        }
        
        public searchModifiedSinceRequestBody(System.DateTime modifyDate)
        {
            this.modifyDate = modifyDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchModifiedSinceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchModifiedSinceResponse", Namespace="http://www.rechtspraak.nl/namespaces/cir01", Order=0)]
        public InsolvencyService.searchModifiedSinceResponseBody Body;
        
        public searchModifiedSinceResponse()
        {
        }
        
        public searchModifiedSinceResponse(InsolvencyService.searchModifiedSinceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.rechtspraak.nl/namespaces/cir01")]
    public partial class searchModifiedSinceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement searchModifiedSinceResult;
        
        public searchModifiedSinceResponseBody()
        {
        }
        
        public searchModifiedSinceResponseBody(System.Xml.XmlElement searchModifiedSinceResult)
        {
            this.searchModifiedSinceResult = searchModifiedSinceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchRemovedSinceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchRemovedSince", Namespace="http://www.rechtspraak.nl/namespaces/cir01", Order=0)]
        public InsolvencyService.searchRemovedSinceRequestBody Body;
        
        public searchRemovedSinceRequest()
        {
        }
        
        public searchRemovedSinceRequest(InsolvencyService.searchRemovedSinceRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.rechtspraak.nl/namespaces/cir01")]
    public partial class searchRemovedSinceRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime modifyDate;
        
        public searchRemovedSinceRequestBody()
        {
        }
        
        public searchRemovedSinceRequestBody(System.DateTime modifyDate)
        {
            this.modifyDate = modifyDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchRemovedSinceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchRemovedSinceResponse", Namespace="http://www.rechtspraak.nl/namespaces/cir01", Order=0)]
        public InsolvencyService.searchRemovedSinceResponseBody Body;
        
        public searchRemovedSinceResponse()
        {
        }
        
        public searchRemovedSinceResponse(InsolvencyService.searchRemovedSinceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.rechtspraak.nl/namespaces/cir01")]
    public partial class searchRemovedSinceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement searchRemovedSinceResult;
        
        public searchRemovedSinceResponseBody()
        {
        }
        
        public searchRemovedSinceResponseBody(System.Xml.XmlElement searchRemovedSinceResult)
        {
            this.searchRemovedSinceResult = searchRemovedSinceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCaseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCase", Namespace="http://www.rechtspraak.nl/namespaces/cir01", Order=0)]
        public InsolvencyService.getCaseRequestBody Body;
        
        public getCaseRequest()
        {
        }
        
        public getCaseRequest(InsolvencyService.getCaseRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.rechtspraak.nl/namespaces/cir01")]
    public partial class getCaseRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string publicationNumber;
        
        public getCaseRequestBody()
        {
        }
        
        public getCaseRequestBody(string publicationNumber)
        {
            this.publicationNumber = publicationNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCaseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCaseResponse", Namespace="http://www.rechtspraak.nl/namespaces/cir01", Order=0)]
        public InsolvencyService.getCaseResponseBody Body;
        
        public getCaseResponse()
        {
        }
        
        public getCaseResponse(InsolvencyService.getCaseResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.rechtspraak.nl/namespaces/cir01")]
    public partial class getCaseResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement getCaseResult;
        
        public getCaseResponseBody()
        {
        }
        
        public getCaseResponseBody(System.Xml.XmlElement getCaseResult)
        {
            this.getCaseResult = getCaseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastUpdateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastUpdate", Namespace="http://www.rechtspraak.nl/namespaces/cir01", Order=0)]
        public InsolvencyService.GetLastUpdateRequestBody Body;
        
        public GetLastUpdateRequest()
        {
        }
        
        public GetLastUpdateRequest(InsolvencyService.GetLastUpdateRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetLastUpdateRequestBody
    {
        
        public GetLastUpdateRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastUpdateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastUpdateResponse", Namespace="http://www.rechtspraak.nl/namespaces/cir01", Order=0)]
        public InsolvencyService.GetLastUpdateResponseBody Body;
        
        public GetLastUpdateResponse()
        {
        }
        
        public GetLastUpdateResponse(InsolvencyService.GetLastUpdateResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.rechtspraak.nl/namespaces/cir01")]
    public partial class GetLastUpdateResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetLastUpdateResult;
        
        public GetLastUpdateResponseBody()
        {
        }
        
        public GetLastUpdateResponseBody(System.Xml.XmlElement GetLastUpdateResult)
        {
            this.GetLastUpdateResult = GetLastUpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchReportsSinceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchReportsSince", Namespace="http://www.rechtspraak.nl/namespaces/cir01", Order=0)]
        public InsolvencyService.searchReportsSinceRequestBody Body;
        
        public searchReportsSinceRequest()
        {
        }
        
        public searchReportsSinceRequest(InsolvencyService.searchReportsSinceRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.rechtspraak.nl/namespaces/cir01")]
    public partial class searchReportsSinceRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime datetimeFrom;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime datetimeTo;
        
        public searchReportsSinceRequestBody()
        {
        }
        
        public searchReportsSinceRequestBody(System.DateTime datetimeFrom, System.DateTime datetimeTo)
        {
            this.datetimeFrom = datetimeFrom;
            this.datetimeTo = datetimeTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchReportsSinceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchReportsSinceResponse", Namespace="http://www.rechtspraak.nl/namespaces/cir01", Order=0)]
        public InsolvencyService.searchReportsSinceResponseBody Body;
        
        public searchReportsSinceResponse()
        {
        }
        
        public searchReportsSinceResponse(InsolvencyService.searchReportsSinceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.rechtspraak.nl/namespaces/cir01")]
    public partial class searchReportsSinceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement searchReportsSinceResult;
        
        public searchReportsSinceResponseBody()
        {
        }
        
        public searchReportsSinceResponseBody(System.Xml.XmlElement searchReportsSinceResult)
        {
            this.searchReportsSinceResult = searchReportsSinceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCaseWithReportsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCaseWithReports", Namespace="http://www.rechtspraak.nl/namespaces/cir01", Order=0)]
        public InsolvencyService.getCaseWithReportsRequestBody Body;
        
        public getCaseWithReportsRequest()
        {
        }
        
        public getCaseWithReportsRequest(InsolvencyService.getCaseWithReportsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.rechtspraak.nl/namespaces/cir01")]
    public partial class getCaseWithReportsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string publicationNumber;
        
        public getCaseWithReportsRequestBody()
        {
        }
        
        public getCaseWithReportsRequestBody(string publicationNumber)
        {
            this.publicationNumber = publicationNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCaseWithReportsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCaseWithReportsResponse", Namespace="http://www.rechtspraak.nl/namespaces/cir01", Order=0)]
        public InsolvencyService.getCaseWithReportsResponseBody Body;
        
        public getCaseWithReportsResponse()
        {
        }
        
        public getCaseWithReportsResponse(InsolvencyService.getCaseWithReportsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.rechtspraak.nl/namespaces/cir01")]
    public partial class getCaseWithReportsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement getCaseWithReportsResult;
        
        public getCaseWithReportsResponseBody()
        {
        }
        
        public getCaseWithReportsResponseBody(System.Xml.XmlElement getCaseWithReportsResult)
        {
            this.getCaseWithReportsResult = getCaseWithReportsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface CIRSoapChannel : InsolvencyService.CIRSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class CIRSoapClient : System.ServiceModel.ClientBase<InsolvencyService.CIRSoap>, InsolvencyService.CIRSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CIRSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CIRSoapClient.GetBindingForEndpoint(endpointConfiguration), CIRSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CIRSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CIRSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CIRSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CIRSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CIRSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InsolvencyService.searchByDateResponse> InsolvencyService.CIRSoap.searchByDateAsync(InsolvencyService.searchByDateRequest request)
        {
            return base.Channel.searchByDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<InsolvencyService.searchByDateResponse> searchByDateAsync(System.DateTime date, string court, InsolvencyService.ArrayOfString pubType)
        {
            InsolvencyService.searchByDateRequest inValue = new InsolvencyService.searchByDateRequest();
            inValue.Body = new InsolvencyService.searchByDateRequestBody();
            inValue.Body.date = date;
            inValue.Body.court = court;
            inValue.Body.pubType = pubType;
            return ((InsolvencyService.CIRSoap)(this)).searchByDateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InsolvencyService.searchInsolvencyIDResponse> InsolvencyService.CIRSoap.searchInsolvencyIDAsync(InsolvencyService.searchInsolvencyIDRequest request)
        {
            return base.Channel.searchInsolvencyIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<InsolvencyService.searchInsolvencyIDResponse> searchInsolvencyIDAsync(string insolvencyID, string court)
        {
            InsolvencyService.searchInsolvencyIDRequest inValue = new InsolvencyService.searchInsolvencyIDRequest();
            inValue.Body = new InsolvencyService.searchInsolvencyIDRequestBody();
            inValue.Body.insolvencyID = insolvencyID;
            inValue.Body.court = court;
            return ((InsolvencyService.CIRSoap)(this)).searchInsolvencyIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InsolvencyService.searchNaturalPersonResponse> InsolvencyService.CIRSoap.searchNaturalPersonAsync(InsolvencyService.searchNaturalPersonRequest request)
        {
            return base.Channel.searchNaturalPersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<InsolvencyService.searchNaturalPersonResponse> searchNaturalPersonAsync(string prefix, string surname, System.DateTime dateOfBirth, string postalCode, int houseNumber)
        {
            InsolvencyService.searchNaturalPersonRequest inValue = new InsolvencyService.searchNaturalPersonRequest();
            inValue.Body = new InsolvencyService.searchNaturalPersonRequestBody();
            inValue.Body.prefix = prefix;
            inValue.Body.surname = surname;
            inValue.Body.dateOfBirth = dateOfBirth;
            inValue.Body.postalCode = postalCode;
            inValue.Body.houseNumber = houseNumber;
            return ((InsolvencyService.CIRSoap)(this)).searchNaturalPersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InsolvencyService.searchUndertakingResponse> InsolvencyService.CIRSoap.searchUndertakingAsync(InsolvencyService.searchUndertakingRequest request)
        {
            return base.Channel.searchUndertakingAsync(request);
        }
        
        public System.Threading.Tasks.Task<InsolvencyService.searchUndertakingResponse> searchUndertakingAsync(string name, string commercialRegisterID, string postalCode, int houseNumber)
        {
            InsolvencyService.searchUndertakingRequest inValue = new InsolvencyService.searchUndertakingRequest();
            inValue.Body = new InsolvencyService.searchUndertakingRequestBody();
            inValue.Body.name = name;
            inValue.Body.commercialRegisterID = commercialRegisterID;
            inValue.Body.postalCode = postalCode;
            inValue.Body.houseNumber = houseNumber;
            return ((InsolvencyService.CIRSoap)(this)).searchUndertakingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InsolvencyService.searchModifiedSinceResponse> InsolvencyService.CIRSoap.searchModifiedSinceAsync(InsolvencyService.searchModifiedSinceRequest request)
        {
            return base.Channel.searchModifiedSinceAsync(request);
        }
        
        public System.Threading.Tasks.Task<InsolvencyService.searchModifiedSinceResponse> searchModifiedSinceAsync(System.DateTime modifyDate)
        {
            InsolvencyService.searchModifiedSinceRequest inValue = new InsolvencyService.searchModifiedSinceRequest();
            inValue.Body = new InsolvencyService.searchModifiedSinceRequestBody();
            inValue.Body.modifyDate = modifyDate;
            return ((InsolvencyService.CIRSoap)(this)).searchModifiedSinceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InsolvencyService.searchRemovedSinceResponse> InsolvencyService.CIRSoap.searchRemovedSinceAsync(InsolvencyService.searchRemovedSinceRequest request)
        {
            return base.Channel.searchRemovedSinceAsync(request);
        }
        
        public System.Threading.Tasks.Task<InsolvencyService.searchRemovedSinceResponse> searchRemovedSinceAsync(System.DateTime modifyDate)
        {
            InsolvencyService.searchRemovedSinceRequest inValue = new InsolvencyService.searchRemovedSinceRequest();
            inValue.Body = new InsolvencyService.searchRemovedSinceRequestBody();
            inValue.Body.modifyDate = modifyDate;
            return ((InsolvencyService.CIRSoap)(this)).searchRemovedSinceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InsolvencyService.getCaseResponse> InsolvencyService.CIRSoap.getCaseAsync(InsolvencyService.getCaseRequest request)
        {
            return base.Channel.getCaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<InsolvencyService.getCaseResponse> getCaseAsync(string publicationNumber)
        {
            InsolvencyService.getCaseRequest inValue = new InsolvencyService.getCaseRequest();
            inValue.Body = new InsolvencyService.getCaseRequestBody();
            inValue.Body.publicationNumber = publicationNumber;
            return ((InsolvencyService.CIRSoap)(this)).getCaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InsolvencyService.GetLastUpdateResponse> InsolvencyService.CIRSoap.GetLastUpdateAsync(InsolvencyService.GetLastUpdateRequest request)
        {
            return base.Channel.GetLastUpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<InsolvencyService.GetLastUpdateResponse> GetLastUpdateAsync()
        {
            InsolvencyService.GetLastUpdateRequest inValue = new InsolvencyService.GetLastUpdateRequest();
            inValue.Body = new InsolvencyService.GetLastUpdateRequestBody();
            return ((InsolvencyService.CIRSoap)(this)).GetLastUpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InsolvencyService.searchReportsSinceResponse> InsolvencyService.CIRSoap.searchReportsSinceAsync(InsolvencyService.searchReportsSinceRequest request)
        {
            return base.Channel.searchReportsSinceAsync(request);
        }
        
        public System.Threading.Tasks.Task<InsolvencyService.searchReportsSinceResponse> searchReportsSinceAsync(System.DateTime datetimeFrom, System.DateTime datetimeTo)
        {
            InsolvencyService.searchReportsSinceRequest inValue = new InsolvencyService.searchReportsSinceRequest();
            inValue.Body = new InsolvencyService.searchReportsSinceRequestBody();
            inValue.Body.datetimeFrom = datetimeFrom;
            inValue.Body.datetimeTo = datetimeTo;
            return ((InsolvencyService.CIRSoap)(this)).searchReportsSinceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InsolvencyService.getCaseWithReportsResponse> InsolvencyService.CIRSoap.getCaseWithReportsAsync(InsolvencyService.getCaseWithReportsRequest request)
        {
            return base.Channel.getCaseWithReportsAsync(request);
        }
        
        public System.Threading.Tasks.Task<InsolvencyService.getCaseWithReportsResponse> getCaseWithReportsAsync(string publicationNumber)
        {
            InsolvencyService.getCaseWithReportsRequest inValue = new InsolvencyService.getCaseWithReportsRequest();
            inValue.Body = new InsolvencyService.getCaseWithReportsRequestBody();
            inValue.Body.publicationNumber = publicationNumber;
            return ((InsolvencyService.CIRSoap)(this)).getCaseWithReportsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CIRSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CIRSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CIRSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://webservice.rechtspraak.nl/cir.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.CIRSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://webservice.rechtspraak.nl/cir.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            CIRSoap,
            
            CIRSoap12,
        }
    }
}
